### ISSUE TITLE
Missing data due to server going read-only mode

### ISSUE THREAD

**Issue by jygh98** [erdl/scrape-util#2]
When the server went to read-only mode, our cron jobs was also affected and for that, we have a short span of missing data between 8/14/2017 11:17 AM to 8/16/2017 10:25 AM.

**Comment by carlosviansi** [comment]
@jygh98 can you also specify how you obtained the time stamps? We need to work on methods to inspect holes in the data anyway. This is a good starting point.

**Comment by jygh98** [comment]
So the projects affected were marine-center-egauge, uhm-frog, maui-egauge, and dhhl.  How i obtained these timestamps was by viewing the timestamps of the output, for example inside the dhhl output folder this is what i see

![sdfs](https://user-images.githubusercontent.com/25787662/29397710-8fd1adb8-82b3-11e7-8647-d35991cad4e0.png)



As we know these projects are set up with to a hourly cron job, and we can see that there's a gap that is present in the other projects also.  Something interesting to note is how big that csv file is when the server came back on, im assuming that scrape util does keep note of when the last export was and continues from there.

**Comment by jygh98** [comment]
I think it would be beneficial to create a script that would check for missing gaps in the database.

**Comment by carlosviansi** [comment]
@jygh98 I agree. Why don't you go ahead and create an issue for that so we plan to do that as a new feature? I guess before we go over there, however, we still need to know how to pull data from webctrl. Could you also create an issue for that?

**Comment by carlosviansi** [comment]
Associated issue to check reading gaps in the database is #4. Closing this issue.
