### ISSUE TITLE
Document how Forrest Scrape Utils Pull Data from Web CTRL

### ISSUE THREAD

**Issue by jygh98** [erdl/scrape-util#3]
This issue diverges from #5, in that the documentation provided here is for the already existing code. Contrary to egauge, which provides a nice API document to request data and requires no authorization, little is known on how the data acquisition is done through webctrl scrape-util. Documentation will be added directly to the wiki.

**Comment by jygh98** [comment]
# WebCtrl in Scrape-Util
In the webctrl acquisition step, scrape-util makes an [http post request](https://github.com/erdl/scrape-util/blob/master/src/acquire/webctrl.py#L186) 
>    req = requests.post(uri,params=params,auth=tuple(auth))

as suggested in the documentation for the [BulkTrendServer](https://github.com/alclabs/BulkTrendServer/blob/master/README.md), an add-on for WebCtrl that allows you to efficiently pull data from the webctrl server.  With the BulkTrendServer add-on, scrape-util is able to include parameters such as specific sensor ids, start and end datetimes, and the format of how the data is all returned in.  Also as mentioned there is authorization required to pull the data which is done by the add-on.

**Comment by carlosviansi** [comment]
Were you able to execute this directly from the terminal without all the dependencies Forrest script requires? 

Currently it is needed to understand how "uri", "params", and "auth" looks like. We would like to be able to do something as simple as pasting in the browser, as we did in egauge, or if not possible due to the authentication step, to quickly do so calling a function and passing the necessary string information a request.post function.

**Comment by jygh98** [comment]
Yes I was able to execute just the requests.post line with the parameters in its place and does make the post request directly from the terminal.

the uri is the base link: "http://www.soest.hawaii.edu/hneienergy/bulktrendserver/read"

params is a dictionary of the variables:
{'id': 'some_sensor_id', 'start': '2017-08-31', 'end': '2017-09-01', 'format': 'json'}

auth is a tuple in the format: ('user', 'pass')

I don't think it is possible to do what we did with the egauges and be able to add the necessary parameters within the url as the authentication step opens up as a form field.  However the project does call a function that passes the necessary parameters above and makes the post request.

**Comment by carlosviansi** [comment]
I think the easiest way for this issue to be realized is mentioning on the Notebook of #5 how it is able to request previous data, and how it relates to Forrest code as an addendum. As such, I will close this issue for now!

**Comment by jygh98** [comment]
```
import requests

uri = 'http://www.soest.hawaii.edu/hneienergy/bulktrendserver/read'

params = {'id': 'ABSPATH:1:#frog1_duct_sensors_1/m030', 'start': '2017-09-13', 'end': '2017-09-13', 'format': 'json'}

auth = ('apitest', 'apipass')

req = requests.post(uri, params = params, auth=tuple(auth))

```
